/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package questions;

import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Duran
 */
public class FrmMenu extends javax.swing.JFrame {
    ClsProperties propiedad = new ClsProperties();
    //int regper = 0;
    //int regmat = 0;
    //int regpre = 0;
    ArrayList<Object> personas = new ArrayList<>();
    ArrayList<Object> materias = new ArrayList<>();
    ArrayList<Object> preguntas = new ArrayList<>();
    ArrayList<Object> preguntasmat = new ArrayList<>();
     
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        ClsIOManager controller = new ClsIOManager();
        tbppersonas.setEnabledAt(2, false);
        tbppersonas.setEnabledAt(3, false);
        //tbppersonas.setEnabledAt(4, false);
        personas = controller.extraer("personas.dat");
        materias = controller.extraer("materias.dat");
        preguntas = controller.extraer("preguntas.dat");
        //preguntasmat = controller.listar("preguntas.dat", 1);
        if(materias.size() > 0 ){
            tbppersonas.setEnabledAt(2, true);
            preguntasmat = controller.listar("preguntas.dat", cmbmatpre.getSelectedIndex());
        }
        
        llenarCombo();
        btnmodificar.setEnabled(false);
        btnborrar.setEnabled(false);
        btnmodificarm.setEnabled(false);
        btneliminarm.setEnabled(false);
        btnmodificarpre.setEnabled(false);
        //tbppersonas.getComponent(1).setEnabled(false);
        

        //jppersonas.setEnabled(false);
    }

    public void llenarPerfil(){
        Object objeto [] = {"Administrador","Jugador"};
        cmbperfil.setModel(new javax.swing.DefaultComboBoxModel(objeto));
    }
    public void llenarCombo(){
        //registro = (int)propiedad.leer("personas");
        if(personas.size() > 0 ){
            //regper= personas.size();
            cmbusuarios.setEnabled(true);
            ClsIOManager controller = new ClsIOManager();
            personas = controller.extraer("personas.dat");
            cmbusuarios.setModel(new javax.swing.DefaultComboBoxModel(personas.toArray()));
        }else{
            //Object [] objeto = new Object[1];
            //objeto[0] = "------";
            //cmbusuarios.setModel(new javax.swing.DefaultComboBoxModel(objeto));
            cmbusuarios.setEnabled(false);
            btnmodificar.setEnabled(false);
            btnborrar.setEnabled(false);
            //registro++;
        }
        
        if(materias.size() > 0 ){
            tbppersonas.setEnabledAt(2, true);
            //regmat= materias.size();
            cmbmateria.setEnabled(true);
            cmbmatpre.setEnabled(true);
            ClsIOManager controller = new ClsIOManager();
            materias = controller.extraer("materias.dat");
            cmbmateria.setModel(new javax.swing.DefaultComboBoxModel(materias.toArray()));
            cmbmatpre.setModel(new javax.swing.DefaultComboBoxModel(materias.toArray()));
        }else{
            cmbmateria.setEnabled(false);
            cmbmatpre.setEnabled(false);
            btnmodificarm.setEnabled(false);
            btneliminarm.setEnabled(false);
            //registro++;
        }
        
        if(preguntas.size() > 0 ){
            //regpre= preguntas.size();
            cmbpreguntasmat.setEnabled(true);
            ClsIOManager controller = new ClsIOManager();
            preguntasmat = controller.listar("preguntas.dat",cmbmatpre.getSelectedIndex());
            cmbpreguntasmat.setModel(new javax.swing.DefaultComboBoxModel(preguntasmat.toArray()));
        }else{
            cmbpreguntasmat.setEnabled(false);
            btnmodificar.setEnabled(false);
            btnborrar.setEnabled(false);
            //registro++;
        }
        
    }
    
    public void limpiar(){
        txtnombreu.setText(null);
        txtapellidou.setText(null);
        txtnombrem.setText(null);
        txtareapre.setText(null);
        txtcedula.setText(null);
        txtcontraseña.setText(null);
        txtpass.setText(null);
        lblmensaje.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbppersonas = new javax.swing.JTabbedPane();
        jppersonas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtnombreu = new javax.swing.JTextField();
        txtapellidou = new javax.swing.JTextField();
        btninsertar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        cmbusuarios = new javax.swing.JComboBox();
        cmbperfil = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpuntaje = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        lblmensaje = new javax.swing.JLabel();
        jpmaterias = new javax.swing.JPanel();
        cmbmateria = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtnombrem = new javax.swing.JTextField();
        btninsertarm = new javax.swing.JButton();
        btnmodificarm = new javax.swing.JButton();
        btneliminarm = new javax.swing.JButton();
        jppreguntas = new javax.swing.JPanel();
        btninsertarpre = new javax.swing.JButton();
        cmbpreguntasmat = new javax.swing.JComboBox();
        cmbmatpre = new javax.swing.JComboBox();
        btnmodificarpre = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareapre = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jprespuestas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");

        tbppersonas.setName(""); // NOI18N

        jLabel3.setText("Nombre:");

        jLabel1.setText("Apellido:");

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnborrar.setText("Eliminar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        cmbusuarios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------" }));
        cmbusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbusuariosActionPerformed(evt);
            }
        });

        cmbperfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Jugador" }));
        cmbperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbperfilActionPerformed(evt);
            }
        });

        jLabel7.setText("Contraseña:");

        jLabel8.setText("Repita:");

        jLabel9.setText("Puntaje:");

        txtpuntaje.setEditable(false);
        txtpuntaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpuntaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpuntaje.setText("0.00");

        jLabel10.setText("Cedula:");

        javax.swing.GroupLayout jppersonasLayout = new javax.swing.GroupLayout(jppersonas);
        jppersonas.setLayout(jppersonasLayout);
        jppersonasLayout.setHorizontalGroup(
            jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppersonasLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btninsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jppersonasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnombreu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbusuarios, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbperfil, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppersonasLayout.createSequentialGroup()
                        .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jppersonasLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppersonasLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22)))
                        .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcontraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellidou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppersonasLayout.createSequentialGroup()
                        .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppersonasLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtpuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jppersonasLayout.setVerticalGroup(
            jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppersonasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cmbusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtnombreu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtpuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtapellidou, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jppersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(cmbperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btninsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnborrar)
                .addContainerGap())
        );

        txtnombreu.getAccessibleContext().setAccessibleDescription("");

        tbppersonas.addTab("Usuarios", jppersonas);

        cmbmateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------" }));
        cmbmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmateriaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        btninsertarm.setText("Insertar");
        btninsertarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarmActionPerformed(evt);
            }
        });

        btnmodificarm.setText("Modificar");
        btnmodificarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarmActionPerformed(evt);
            }
        });

        btneliminarm.setText("Eliminar");
        btneliminarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpmateriasLayout = new javax.swing.GroupLayout(jpmaterias);
        jpmaterias.setLayout(jpmateriasLayout);
        jpmateriasLayout.setHorizontalGroup(
            jpmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmateriasLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jpmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpmateriasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnombrem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbmateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btninsertarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminarm, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        jpmateriasLayout.setVerticalGroup(
            jpmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmateriasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cmbmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jpmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombrem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btninsertarm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificarm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminarm)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        tbppersonas.addTab("Materias", jpmaterias);

        btninsertarpre.setText("Insertar");
        btninsertarpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarpreActionPerformed(evt);
            }
        });

        cmbpreguntasmat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", " " }));
        cmbpreguntasmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpreguntasmatActionPerformed(evt);
            }
        });

        cmbmatpre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", " " }));
        cmbmatpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatpreActionPerformed(evt);
            }
        });

        btnmodificarpre.setText("Modificar");
        btnmodificarpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarpreActionPerformed(evt);
            }
        });

        jLabel4.setText("Texto de la Pregunta: ");

        txtareapre.setColumns(20);
        txtareapre.setRows(5);
        jScrollPane1.setViewportView(txtareapre);

        jLabel5.setText("Materias:");

        jLabel6.setText("Preguntas:");

        javax.swing.GroupLayout jppreguntasLayout = new javax.swing.GroupLayout(jppreguntas);
        jppreguntas.setLayout(jppreguntasLayout);
        jppreguntasLayout.setHorizontalGroup(
            jppreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppreguntasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jppreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jppreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4)
                    .addComponent(btninsertarpre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificarpre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbpreguntasmat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbmatpre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jppreguntasLayout.setVerticalGroup(
            jppreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppreguntasLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jppreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbmatpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jppreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbpreguntasmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btninsertarpre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificarpre)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        tbppersonas.addTab("Preguntas", jppreguntas);

        javax.swing.GroupLayout jprespuestasLayout = new javax.swing.GroupLayout(jprespuestas);
        jprespuestas.setLayout(jprespuestasLayout);
        jprespuestasLayout.setHorizontalGroup(
            jprespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        jprespuestasLayout.setVerticalGroup(
            jprespuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        tbppersonas.addTab("Repuestas", jprespuestas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbppersonas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbppersonas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbmatpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatpreActionPerformed
        // TODO add your handling code here:
        ClsIOManager controller = new ClsIOManager();
        preguntasmat = controller.listar("preguntas.dat",cmbmatpre.getSelectedIndex());
        if(preguntasmat.size() > 0 ){
            //regpre= preguntas.size();
            cmbpreguntasmat.setEnabled(true);
            cmbpreguntasmat.setModel(new javax.swing.DefaultComboBoxModel(preguntasmat.toArray()));
        }else{
            cmbpreguntasmat.setEnabled(false);
            btnmodificar.setEnabled(false);
            btnborrar.setEnabled(false);
            //registro++;
        }
    }//GEN-LAST:event_cmbmatpreActionPerformed

    private void cmbpreguntasmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpreguntasmatActionPerformed
        // TODO add your handling code here:
        ClsPregunta pregunta = (ClsPregunta) cmbpreguntasmat.getSelectedItem();
        txtareapre.setText(pregunta.getTexto());
        btninsertarpre.setEnabled(false);
        btnmodificarpre.setEnabled(true);
    }//GEN-LAST:event_cmbpreguntasmatActionPerformed

    private void btninsertarpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarpreActionPerformed
        // TODO add your handling code here:
        ClsIOManager controller = new ClsIOManager();
        ClsPregunta pregunta = new ClsPregunta(propiedad.leer("preguntas"), cmbmatpre.getSelectedIndex() ,txtareapre.getText());
        preguntas.add(pregunta);
        controller.insertar("preguntas.dat", preguntas);
        preguntas = controller.extraer("preguntas.dat");
        llenarCombo();
        propiedad.escribir(propiedad.leer("preguntas")+1, "preguntas");
        limpiar();

    }//GEN-LAST:event_btninsertarpreActionPerformed

    private void btneliminarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarmActionPerformed
        // TODO add your handling code here:
        ClsIOManager controller = new ClsIOManager();

        //ClsPersona persona = (ClsPersona) cmbusuarios.getSelectedItem();
        materias.remove(cmbmateria.getSelectedIndex());
        controller.insertar("materias.dat", materias);
        materias = controller.extraer("materias.dat");
        llenarCombo();
        limpiar();
        btninsertarm.setEnabled(true);
        btnmodificarm.setEnabled(false);
        btneliminarm.setEnabled(false);
    }//GEN-LAST:event_btneliminarmActionPerformed

    private void btnmodificarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarmActionPerformed
        // TODO add your handling code here:
        ClsIOManager controller = new ClsIOManager();
        ClsMateria materia = (ClsMateria) cmbmateria.getSelectedItem();
        materia.setNombre(txtnombrem.getText());
        materias.remove(cmbmateria.getSelectedIndex());
        materias.add(cmbmateria.getSelectedIndex(), materia);
        controller.insertar("materias.dat", materias);
        materias = controller.extraer("materias.dat");
        llenarCombo();
        limpiar();
        btninsertarm.setEnabled(true);
        btnmodificarm.setEnabled(false);
        btneliminarm.setEnabled(false);
    }//GEN-LAST:event_btnmodificarmActionPerformed

    private void btninsertarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarmActionPerformed
        // TODO add your handling code here:
        ClsIOManager controller = new ClsIOManager();
        //controller.escribir("prueba.dat");
        //controller.escribeFichero("prueba.dat");
        ClsMateria materia = new ClsMateria(propiedad.leer("materias"), txtnombrem.getText());
        materias.add(materia);
        //System.out.println(persona.imprimir());
        controller.insertar("materias.dat", materias);
        materias = controller.extraer("materias.dat");
        llenarCombo();
        propiedad.escribir(propiedad.leer("materias")+1, "materias");
        limpiar();
    }//GEN-LAST:event_btninsertarmActionPerformed

    private void cmbmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmateriaActionPerformed
        // TODO add your handling code here:
        ClsMateria materia = (ClsMateria) cmbmateria.getSelectedItem();
        txtnombrem.setText(materia.getNombre());
        btninsertarm.setEnabled(false);
        btnmodificarm.setEnabled(true);
        btneliminarm.setEnabled(true);
    }//GEN-LAST:event_cmbmateriaActionPerformed

    private void cmbperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbperfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbperfilActionPerformed

    private void cmbusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbusuariosActionPerformed
        // TODO add your handling code here:

        ClsPersona persona = (ClsPersona) cmbusuarios.getSelectedItem();
        txtnombreu.setText(persona.getNombre());
        txtapellidou.setText(persona.getApellido());
        cmbperfil.setSelectedItem(persona.getPerfil());
        //txtcontraseña.setText(persona.getContraseña());
        txtcedula.setText(persona.getCedula());
        btninsertar.setEnabled(false);
        btnmodificar.setEnabled(true);
        btnborrar.setEnabled(true);
    }//GEN-LAST:event_cmbusuariosActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        ClsIOManager controller = new ClsIOManager();

        //ClsPersona persona = (ClsPersona) cmbusuarios.getSelectedItem();
        personas.remove(cmbusuarios.getSelectedIndex());
        controller.insertar("personas.dat", personas);
        personas = controller.extraer("personas.dat");
        llenarCombo();
        limpiar();
        btninsertar.setEnabled(true);
        btnmodificar.setEnabled(false);
        btnborrar.setEnabled(false);
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        //
        ClsIOManager controller = new ClsIOManager();
        if(txtcontraseña.getText() == ""){
            ClsPersona persona = (ClsPersona) cmbusuarios.getSelectedItem();
            persona.setNombre(txtnombreu.getText());
            persona.setApellido(txtapellidou.getText());
            persona.setPerfil((String) cmbperfil.getSelectedItem());
            persona.setCedula(txtcedula.getText());
            personas.remove(cmbusuarios.getSelectedIndex());
            personas.add(cmbusuarios.getSelectedIndex(), persona);
            controller.insertar("personas.dat", personas);
        }else if(txtcontraseña.getText().equals(txtpass.getText()) && txtcontraseña.getText() != "" && txtpass.getText() != ""){
            
            ClsPersona persona = (ClsPersona) cmbusuarios.getSelectedItem();
            persona.setNombre(txtnombreu.getText());
            persona.setApellido(txtapellidou.getText());
            persona.setPerfil((String) cmbperfil.getSelectedItem());
            persona.setCedula(txtcedula.getText());
            persona.setContraseña(txtcontraseña.getText());
            personas.remove(cmbusuarios.getSelectedIndex());
            personas.add(cmbusuarios.getSelectedIndex(), persona);
            controller.insertar("personas.dat", personas);
        }else{
            lblmensaje.setText("Contraseña Incorrecta");
            txtcontraseña.setText(null);
            txtpass.setText(null);
        }
            personas = controller.extraer("personas.dat");
            llenarCombo();
            limpiar();
            btninsertar.setEnabled(true);
            btnmodificar.setEnabled(false);
            btnborrar.setEnabled(false);

    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        // TODO add your handling code here:
        //System.out.println(txtcontraseña.getText());
        if(txtcontraseña.getText().equals("")){
            lblmensaje.setText("Debe Ingresar una contraseña");
            txtcontraseña.setText(null);
            txtpass.setText(null);
        }else if(txtcontraseña.getText().equals(txtpass.getText())){
            ClsIOManager controller = new ClsIOManager();
            ClsPersona persona = new ClsPersona(propiedad.leer("personas"), txtnombreu.getText(), txtapellidou.getText(),(String) cmbperfil.getSelectedItem(),txtcedula.getText() ,txtcontraseña.getText());
            personas.add(persona);
            controller.insertar("personas.dat", personas);
            personas = controller.extraer("personas.dat");
            llenarCombo();
            propiedad.escribir(propiedad.leer("personas")+1, "personas");
            limpiar();
        }else{
            lblmensaje.setText("Contraseña Incorrecta");
            txtcontraseña.setText(null);
            txtpass.setText(null);
        }

    }//GEN-LAST:event_btninsertarActionPerformed

    private void btnmodificarpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarpreActionPerformed
        // TODO add your handling code here:
        ClsIOManager controller = new ClsIOManager();
        ClsPregunta pregunta = (ClsPregunta) cmbpreguntasmat.getSelectedItem();
        pregunta.setTexto(txtareapre.getText());
        System.out.println(pregunta.getId());
        preguntas.remove(pregunta.getId()-1);
        preguntas.add(pregunta.getId()-1, pregunta);
        controller.insertar("preguntas.dat", preguntas);
        preguntas = controller.extraer("preguntas.dat");
        llenarCombo();
        limpiar();
        btninsertarm.setEnabled(true);
        btnmodificarm.setEnabled(false);
        btneliminarm.setEnabled(false);
        
    }//GEN-LAST:event_btnmodificarpreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btneliminarm;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btninsertarm;
    private javax.swing.JButton btninsertarpre;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmodificarm;
    private javax.swing.JButton btnmodificarpre;
    private javax.swing.JComboBox cmbmateria;
    private javax.swing.JComboBox cmbmatpre;
    private javax.swing.JComboBox cmbperfil;
    private javax.swing.JComboBox cmbpreguntasmat;
    private javax.swing.JComboBox cmbusuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpmaterias;
    private javax.swing.JPanel jppersonas;
    private javax.swing.JPanel jppreguntas;
    private javax.swing.JPanel jprespuestas;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTabbedPane tbppersonas;
    private javax.swing.JTextField txtapellidou;
    private javax.swing.JTextArea txtareapre;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtnombrem;
    private javax.swing.JTextField txtnombreu;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtpuntaje;
    // End of variables declaration//GEN-END:variables
}
